import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import profiles from './bodyProfiles.json';
import garments from './garments.json';
import {ease,fitFromEase,levelCompatibility} from './fashionRules.js';
import './style.css';

const app=document.querySelector('#app');
app.innerHTML=`<div class="shell"><header><div><span class="eyebrow">FASHION LANGUAGE STUDIO · V0.1</span><h1>Body → Fit → Fashion Language</h1><p>First working layer: your GLB body library + measurement-aware fitting foundation.</p></div><div class="badge">31 GLB BODY MODELS</div></header><main><aside class="panel controls"><h2>Body Model</h2><label>Group<select id="group"><option value="All">All</option><option>Asian</option><option>Caucasian</option><option>African</option></select></label><label>Gender<select id="gender"><option value="All">All</option><option>Female</option><option>Male</option></select></label><label>Age<select id="age"><option value="All">All</option><option>Adult</option><option>Teen</option><option>Child</option><option>Toddler</option><option>Elderly</option></select></label><label>Model<select id="model"></select></label><div class="divider"></div><h2>Body Measurements</h2><div class="unit"><button class="active" data-unit="cm">cm</button><button data-unit="in">in</button></div><div class="measure-grid">${[['height','Height',170],['shoulder','Shoulder',44],['chest','Chest',96],['waist','Waist',82],['hip','Hip',98],['arm','Arm length',60],['leg','Leg length',78]].map(([id,l,v])=>`<label>${l}<input id="${id}" type="number" value="${v}" step="0.5"><span class="suffix">cm</span></label>`).join('')}</div><button id="mono" class="secondary">Mono / Skin view</button></aside><section class="viewer"><div id="canvas"></div><div class="viewerbar"><span id="status">Loading model…</span><div><button id="front">Front</button><button id="side">Side</button><button id="back">Back</button><button id="reset">Reset</button></div></div></section><aside class="panel fit"><h2>First Garment</h2><div class="card"><strong>Crew Neck T-Shirt</strong><small>Regular · Cotton Jersey · 180 GSM</small><div class="row"><span>Formality</span><b>Level 2</b></div><div class="tags"><span>Minimalist</span><span>Streetwear</span></div></div><label>Size<select id="size"><option>S</option><option selected>M</option><option>L</option><option>XL</option></select></label><div class="fitbox"><div><small>Body chest</small><strong id="bodyChest">96 cm</strong></div><div><small>Garment chest</small><strong id="garmentChest">108 cm</strong></div><div><small>Chest ease</small><strong id="chestEase">+12 cm</strong></div><div><small>Fit reading</small><strong id="fitReading">Regular fit</strong></div></div><h2>Fashion Rule</h2><div class="rule"><b>Level ±1</b><p>This first engine allows garments within one Formaility Level of each other. A future outfit builder will apply this to tops, bottoms and footwear.</p></div><div class="next"><b>Next build layer</b><br>Real T-shirt 3D garment → body collision → fabric/GSM → fit visualization.</div></aside></main></div>`;

const container=document.querySelector('#canvas');
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x111318);
const camera=new THREE.PerspectiveCamera(35,1,0.01,100); camera.position.set(0,1.35,3.2);
const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.outputColorSpace=THREE.SRGBColorSpace; container.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement); controls.enableDamping=true; controls.target.set(0,1.15,0);
scene.add(new THREE.HemisphereLight(0xffffff,0x333333,2.2)); const key=new THREE.DirectionalLight(0xffffff,2.5); key.position.set(2,4,3); scene.add(key);
const grid=new THREE.GridHelper(4,20,0x30343c,0x20242b); scene.add(grid);
let current=null, originalMaterials=[]; const loader=new GLTFLoader();
function resize(){const r=container.getBoundingClientRect(); renderer.setSize(r.width,r.height,false); camera.aspect=r.width/r.height; camera.updateProjectionMatrix();} addEventListener('resize',resize); resize();
function filtered(){const g=document.querySelector('#group').value, ge=document.querySelector('#gender').value,a=document.querySelector('#age').value; return profiles.filter(p=>(g==='All'||p.group===g)&&(ge==='All'||p.gender===ge)&&(a==='All'||p.age===a));}
function fillModels(){const s=document.querySelector('#model'); const list=filtered(); s.innerHTML=list.map(p=>`<option value="${p.id}">${p.label}</option>`).join(''); if(list.length) loadModel(list[0]);}
function loadModel(profile){document.querySelector('#status').textContent=`Loading ${profile.label}…`; if(current){scene.remove(current); current.traverse(o=>{if(o.isMesh){o.geometry.dispose(); if(o.material?.dispose)o.material.dispose();}});} loader.load(`/models/${encodeURIComponent(profile.file)}`,g=>{current=g.scene; current.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true; originalMaterials.push(o.material);}}); const box=new THREE.Box3().setFromObject(current); const size=box.getSize(new THREE.Vector3()); const center=box.getCenter(new THREE.Vector3()); current.position.sub(center); current.position.y+=size.y/2; const scale=2.25/size.y; current.scale.setScalar(scale); scene.add(current); controls.target.set(0,1.05,0); controls.update(); document.querySelector('#status').textContent=`Loaded · ${profile.label}`;},undefined,e=>document.querySelector('#status').textContent=`Model load error: ${e.message||'check filename'}`);}
['group','gender','age'].forEach(id=>document.querySelector('#'+id).addEventListener('change',fillModels)); document.querySelector('#model').addEventListener('change',e=>loadModel(profiles.find(p=>p.id===e.target.value)));
function setView(rot){if(current)current.rotation.y=rot;}
document.querySelector('#front').onclick=()=>setView(0); document.querySelector('#side').onclick=()=>setView(Math.PI/2); document.querySelector('#back').onclick=()=>setView(Math.PI);
document.querySelector('#reset').onclick=()=>{if(current)current.rotation.y=0;camera.position.set(0,1.35,3.2);controls.target.set(0,1.05,0);controls.update();};
document.querySelector('#mono').onclick=()=>{if(!current)return;current.traverse(o=>{if(o.isMesh){if(!o.userData.original)o.userData.original=o.material;o.material=new THREE.MeshStandardMaterial({color:0xb9bcc2,roughness:.82,metalness:0});}})};
let unit='cm'; document.querySelectorAll('.unit button').forEach(b=>b.onclick=()=>{unit=b.dataset.unit;document.querySelectorAll('.unit button').forEach(x=>x.classList.remove('active'));b.classList.add('active');});
function updateFit(){const body=parseFloat(document.querySelector('#chest').value)||0;const size=document.querySelector('#size').value;const g=garments[0].sizes[size];const e=ease(body,g.chest), f=fitFromEase(e);document.querySelector('#bodyChest').textContent=`${body} cm`;document.querySelector('#garmentChest').textContent=`${g.chest} cm`;document.querySelector('#chestEase').textContent=`${e>=0?'+':''}${e} cm`;document.querySelector('#fitReading').textContent=f.label;}
document.querySelector('#chest').addEventListener('input',updateFit);document.querySelector('#size').addEventListener('change',updateFit);
fillModels(); updateFit();
function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera);} animate();
